### ISSUE TITLE
Request uri loses start of it's path if basepath is not present in swaggerspec

### ISSUE THREAD

**Issue by pakarjon** [djfdyuruiry/swagger2-postman-generator#4]
When converting swagger 2.0 spec to postman collection, my request paths `/dir1/dir2` lose their first directory, becoming only `/dir2`. 

This seems to happen because swaggerspec does not contain any basepath and in convert.js setBasePath method, the uri's host is set to http:///dir1/dir2.
```
else {
                this.basePath = 'http://' + this.basePath;
}
```
When request.url is later modified in function processPostmanCollection: ` request.url = request.url.replace(/:\/\/.+?\//,  "://{{host}}:{{port}}/");`, it turns from `http:///dir1/dir2` to `{{scheme}}://{{host}}:{{port}}/dir2`.

I managed to fix it by replacing "+?" from that replace regex with ".*?". I don't know if the real problem is the missing basepath or that regex, but for my scenario, fixing that regex worked.

EDIT: Maybe better regex fix would be `[^/]*`  instead of `.*?`.

**Comment by djfdyuruiry** [comment]
This is a good point, updated the code the simply replace `://` and anything after it before the first `/` with `://{{host}}:{{port}}` thanks @pakarjon (Fixed in npm package version 2.1.1)
