### ISSUE TITLE
name of request is empty

### ISSUE THREAD

**Issue by ghost** [djfdyuruiry/swagger2-postman-generator#5]
when converting a swagger (OAS 2.0) to a postman collection, the "name" of the requests are not defined leading to empty field in postman. I guess the "name" should be the operationId ...
am i using this incorrectly ?

**Comment by djfdyuruiry** [comment]
I have not had a chance to look into this issue due to other commitments. I will have an investigation on the side hopefully soon to see if I can replicate your issue, and if so will try to add a fix. For now I will close this issue due to it being so old.
